name: GitBook Build

on:
  push:
    branches:
      - main  # 替换为你的主分支名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cache GitBook dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm-global
        key: ${{ runner.os }}-node-global-${{ hashFiles('**/book.json') }}
        restore-keys: |
          ${{ runner.os }}-node-global-

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '10.24.1'

    - name: Install GitBook dependencies
      run: |
        if [ ! -f ~/.npm-global/bin/gitbook ]; then
          npm install -g gitbook-cli
        fi

    - name: Restore Node.js modules from cache
      run: |
        npm ci

    - name: try install sitemap-general plugins
      run: |
        npm install gitbook-plugin-sitemap-general

    - name: GitBook install plugins
      run: |
        gitbook install

    - name: Build GitBook in docs directory
      run: |
        gitbook build ./ ./docs

    - name: Configure Git
      run: |
        if [ -z "$(git config --get user.email)" ]; then
          git config --global user.email "actions@github.com"
        fi
        if [ -z "$(git config --get user.name)" ]; then
          git config --global user.name "GitHub Actions"
        fi

    - name: Commit and push changes
      run: |
        git status
        git pull origin main
        git add -A
        git diff-index --quiet HEAD || git commit -m "Update GitBook build [skip ci]"
        git push -u "${{ secrets.Action }}"
