name: GitBook Build

on:
  push:
    branches:
      - main  # 换成你的主分支名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: unInstall Node
      run: |
        apt-get uninstall node

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/*.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cache GitBook CLI
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm-global
        key: ${{ runner.os }}-node-global-${{ hashFiles('**/*.json') }}
        restore-keys: |
          ${{ runner.os }}-node-global-

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '10.24.1'  # 设置为你需要的 Node.js 版本

    - name: Install GitBook
      run: |
        npm install -g gitbook-cli
        gitbook install

    - name: Build GitBook in docs directory
      run: |
        gitbook build ./docs

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add docs
        git commit -m "Update GitBook build [skip ci]"
        git push
